export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  DOCTOR = 'DOCTOR',
  PATIENT = 'PATIENT',
  NURSE = 'NURSE',
  STAFF = 'STAFF',
  CLINIC_ADMIN = 'CLINIC_ADMIN',
  CLINIC_STAFF = 'CLINIC_STAFF',
}
